use_frameworks!

target 'LGBPhotoBrowser_Example', :exclusive => true do
  pod 'LGBPhotoBrowser', :path => '../'

  pod 'YYWebImage', '~> 1.0.3'
end

target 'LGBPhotoBrowser_Tests', :exclusive => true do
  pod 'LGBPhotoBrowser', :path => '../'

  
end
